package com.landray.kmss.xdf.webservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0 2012-12-25T17:01:42.835+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "IAttMainWebServiceService", wsdlLocation = "http://192.168.25.169:9080/ixdf/sys/webservice/attMainWebService?wsdl", targetNamespace = "http://webservice.xdf.kmss.landray.com/")
public class IAttMainWebServiceService extends Service {

	public static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName(
			"http://webservice.xdf.kmss.landray.com/",
			"IAttMainWebServiceService");
	public final static QName IAttMainWebServicePort = new QName(
			"http://webservice.xdf.kmss.landray.com/", "IAttMainWebServicePort");
	

	public IAttMainWebServiceService(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public IAttMainWebServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public IAttMainWebServiceService() {
		super(WSDL_LOCATION, SERVICE);
	}

	/**
	 * 
	 * @return returns IAttMainWebService
	 */
	@WebEndpoint(name = "IAttMainWebServicePort")
	public IAttMainWebService getIAttMainWebServicePort() {
		return super.getPort(IAttMainWebServicePort, IAttMainWebService.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns IAttMainWebService
	 */
	@WebEndpoint(name = "IAttMainWebServicePort")
	public IAttMainWebService getIAttMainWebServicePort(
			WebServiceFeature... features) {
		return super.getPort(IAttMainWebServicePort, IAttMainWebService.class,
				features);
	}

}
