package com.landray.kmss.xdf.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-12-25T17:01:42.819+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://webservice.xdf.kmss.landray.com/", name = "IAttMainWebService")
public interface IAttMainWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAttMain", targetNamespace = "http://webservice.xdf.kmss.landray.com/", className = "com.landray.kmss.xdf.webservice.attmain.GetAttMain")
    @WebMethod
    @ResponseWrapper(localName = "getAttMainResponse", targetNamespace = "http://webservice.xdf.kmss.landray.com/", className = "com.landray.kmss.xdf.webservice.attmain.GetAttMainResponse")
    public ReturnMsg getAttMain(
        @WebParam(name = "attMain", targetNamespace = "")
        AttMain attMain
    ) throws Exception;

    @WebResult(name = "returnMsg", targetNamespace = "")
    @RequestWrapper(localName = "addAttMain", targetNamespace = "http://webservice.xdf.kmss.landray.com/", className = "com.landray.kmss.xdf.webservice.attmain.AddAttMain")
    @WebMethod
    @ResponseWrapper(localName = "addAttMainResponse", targetNamespace = "http://webservice.xdf.kmss.landray.com/", className = "com.landray.kmss.xdf.webservice.attmain.AddAttMainResponse")
    public ReturnMsg addAttMain(
        @WebParam(name = "attMain", targetNamespace = "")
        AttMain attMain
    ) throws Exception;
}
