
package com.landray.kmss.xdf.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-12-25T17:01:42.525+08:00
 * Generated source version: 2.7.0
 * 
 */
public final class IAttMainWebService_IAttMainWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.xdf.kmss.landray.com/", "IAttMainWebServiceService");

    private IAttMainWebService_IAttMainWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IAttMainWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IAttMainWebServiceService ss = new IAttMainWebServiceService(wsdlURL, SERVICE_NAME);
        IAttMainWebService port = ss.getIAttMainWebServicePort();  
        
        {
        System.out.println("Invoking getAttMain...");
        AttMain _getAttMain_attMain = new AttMain();
        _getAttMain_attMain.setContentType("ContentType-788490342");
        _getAttMain_attMain.setDocument(false);
        java.util.List<java.lang.String> _getAttMain_attMainFilePaths = new java.util.ArrayList<java.lang.String>();
        java.lang.String _getAttMain_attMainFilePathsVal1 = "_getAttMain_attMainFilePathsVal-1611006909";
        _getAttMain_attMainFilePaths.add(_getAttMain_attMainFilePathsVal1);
        _getAttMain_attMain.getFilePaths().addAll(_getAttMain_attMainFilePaths);
        _getAttMain_attMain.setModelId("ModelId166988325");
        _getAttMain_attMain.setModelName("ModelName753990865");
        try {
            ReturnMsg _getAttMain__return = port.getAttMain(_getAttMain_attMain);
            System.out.println("getAttMain.result=" + _getAttMain__return);

        } catch (Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking addAttMain...");
        AttMain _addAttMain_attMain = new AttMain();
        _addAttMain_attMain.setContentType("ContentType-271313252");
        _addAttMain_attMain.setDocument(false);
        java.util.List<java.lang.String> _addAttMain_attMainFilePaths = new java.util.ArrayList<java.lang.String>();
        java.lang.String _addAttMain_attMainFilePathsVal1 = "_addAttMain_attMainFilePathsVal1234812535";
        _addAttMain_attMainFilePaths.add(_addAttMain_attMainFilePathsVal1);
        _addAttMain_attMain.getFilePaths().addAll(_addAttMain_attMainFilePaths);
        _addAttMain_attMain.setModelId("ModelId1374534950");
        _addAttMain_attMain.setModelName("ModelName1549174243");
        try {
            ReturnMsg _addAttMain__return = port.addAttMain(_addAttMain_attMain);
            System.out.println("addAttMain.result=" + _addAttMain__return);

        } catch (Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
