
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.landray.kmss.xdf.webservice;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-12-25T16:59:40.420+08:00
 * Generated source version: 2.7.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "IToAdTdsWebServiceService",
                      portName = "IToAdTdsWebServicePort",
                      targetNamespace = "http://webservice.xdf.kmss.landray.com/",
                      wsdlLocation = "http://192.168.25.169:9080/ixdf/sys/webservice/toAdTdsWebService?wsdl",
                      endpointInterface = "com.landray.kmss.xdf.webservice.IToAdTdsWebService")
                      
public class IToAdTdsWebServiceImpl implements IToAdTdsWebService {

    private static final Logger LOG = Logger.getLogger(IToAdTdsWebServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.landray.kmss.xdf.webservice.IToAdTdsWebService#addPerson(com.landray.kmss.xdf.webservice.SysOrgUser  user )*
     */
    public int addPerson(com.landray.kmss.xdf.webservice.SysOrgUser user) throws Exception    { 
        LOG.info("Executing operation addPerson");
        System.out.println(user);
        try {
            int _return = -482372432;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

}
