
package com.landray.kmss.xdf.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-12-25T16:59:40.134+08:00
 * Generated source version: 2.7.0
 * 
 */
public final class IToAdTdsWebService_IToAdTdsWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.xdf.kmss.landray.com/", "IToAdTdsWebServiceService");

    private IToAdTdsWebService_IToAdTdsWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IToAdTdsWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IToAdTdsWebServiceService ss = new IToAdTdsWebServiceService(wsdlURL, SERVICE_NAME);
        IToAdTdsWebService port = ss.getIToAdTdsWebServicePort();  
        
        {
        System.out.println("Invoking addPerson...");
        com.landray.kmss.xdf.webservice.SysOrgUser _addPerson_user = new com.landray.kmss.xdf.webservice.SysOrgUser();
        _addPerson_user.setCompanyId("CompanyId1588032171");
        _addPerson_user.setDeptId("DeptId1784154908");
        _addPerson_user.setFdIsEmp("FdIsEmp334694984");
        _addPerson_user.setLoginName("LoginName-844661514");
        _addPerson_user.setMail("Mail1508406232");
        _addPerson_user.setName("Name900429167");
        byte[] _addPerson_userPotoImg = new byte[] {};
        _addPerson_user.setPotoImg(_addPerson_userPotoImg);
        _addPerson_user.setPwd("Pwd64671059");
        _addPerson_user.setSfz("Sfz-991988693");
        _addPerson_user.setTel("Tel-2091121959");
        _addPerson_user.setTitle("Title1629715719");
        try {
            int _addPerson__return = port.addPerson(_addPerson_user);
            System.out.println("addPerson.result=" + _addPerson__return);

        } catch (Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
