package com.landray.kmss.xdf.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-12-25T16:59:40.433+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://webservice.xdf.kmss.landray.com/", name = "IToAdTdsWebService")
public interface IToAdTdsWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addPerson", targetNamespace = "http://webservice.xdf.kmss.landray.com/", className = "com.landray.kmss.xdf.webservice.AddPerson")
    @WebMethod
    @ResponseWrapper(localName = "addPersonResponse", targetNamespace = "http://webservice.xdf.kmss.landray.com/", className = "com.landray.kmss.xdf.webservice.AddPersonResponse")
    public int addPerson(
        @WebParam(name = "user", targetNamespace = "")
        com.landray.kmss.xdf.webservice.SysOrgUser user
    ) throws Exception;
}
